### ISSUE TITLE
Server Only Rendering

### ISSUE THREAD

**Issue by rndm2** [tbranyen/backbone.layoutmanager#489]
We are using backbone.layoutmanager with node js to render template on the server:
```
var html = (new componentClass()).setData(data).render().$el.html();
```
On the client side we are initializng view like this:
```
return (new componentClass()).setData(__DATA__).touchHTML();
...
touchHTML: function() {
    this.el.innerHTML = '';
    this.render();
}
```
As you can see, we are doing the same job on the server and then on the client again. 
Do LayoutManager have some method or workaround to compare markup on client (like react) with server-rendered and render again only if no markup or markups are differrent? Or just set server-rendered markup to LayoutManager and do not render it on the client at all.

**Comment by tbranyen** [comment]
Quite a few ways to handle this. Since React uses a Virtual Dom, you could theoretically integrate virtual-dom into your render cycle, but that might be a bit of work. If you're sure the data is the same being passed to `setData` you could add a `data-rendered-via-server` tag to your elements on the server, and then on the client use a conditional to NOP on the first render (remove the attr) and then subsequent renders would work just fine.

**Comment by rndm2** [comment]
I tried to do this, but problem is that I need to rewrite LayoutManager render function because no function to handle already rendered markup and set views in LayoutManager

**Comment by tbranyen** [comment]
@rndm2 it might be easier than that. Maybe this?

``` javascript
LayoutManager.configure({
  html: function($el, html) {
    // Do something with the element and markup here...
  }
});
```

This method used to be documented along with the other abstractions we have, but I can't seem to find where they went ATM.
