### ISSUE TITLE
suggest add scopeValue option

### ISSUE THREAD

**Issue by icai** [tbranyen/backbone.layoutmanager#499]
why? 
if parent View have a value, while it’s all child view also need this value. so if provide a option to set in parent view, the child view auto add this scopeValue, that would be save a lot of job.

**Comment by tbranyen** [comment]
Thanks for the suggestion @icai! I think this could be solved already by passing a reference to all the childViews. This would align well with data down and actions up.

Unfortunately I don't really have the time to maintain LayoutManager, since I don't use it. If you end up learning the codebase well and think you could land and maintain the PR, feel free to send it :+1:
